### ISSUE TITLE
Only one drone transmitting

### ISSUE THREAD

**Issue by sparkyws** [jjshoots/RemoteIDSpoofer#1]
I can only get one fake drone, not a spawn of 16

**Comment by jjshoots** [comment]
Hi! Thanks for the issue, this has just been fixed in #3. Lmk if you still encounter this issue. :)

**Comment by sparkyws** [comment]
> Hi! Thanks for the issue, this has just been fixed in #3. Lmk if you still encounter this issue. :)

Hi Again, thanks for this, its working better but (sorry) only 4 drones are active nearby , the other 12 are not transmitting there coordinates. Also is it posible to have more than one operator. Also please have a look at our drone club its at https://greyarro.ws/  I am sparkyws  thanks

**Comment by jjshoots** [comment]
@WayneStarkey Are you using your fork of the RemoteIDSpoofer code? If so, I think you need to merge from master. You are only up to date with #2, not #3.

By default, all the drones have a different operator ID, so technically there are 16 operators.

**Comment by sparkyws** [comment]
No I am using your latest release as from this morning

![image](https://github.com/jjshoots/RemoteIDSpoofer/assets/60844478/387917f1-9f79-4a37-a93a-4a0b943a60b3)

![image](https://github.com/jjshoots/RemoteIDSpoofer/assets/60844478/d0e8183c-8492-409c-aa7e-3ec65317b163)

**Comment by jjshoots** [comment]
I'm not too sure what could be the issue then, the NodeMCU has some reservations about packets it likes to send and which it doesn't and I haven't figured out why yet. It seems to work on my end. Could you try the OpenDroneID app and see if that works? Also which app are you using for the scan?

**Comment by jjshoots** [comment]
Now that you mention it, a bunch of the drones on my end seem to be spawning without a valid GPS location. I'll look into it soon. Thanks again for the report!

**Comment by sparkyws** [comment]
I am using a TTGO t-display with an app from http://uassentry.com/
I am also using OpenDroneID and that's when I realised the GPS coordinates weren't valid on some of the spoofed drones

Is there a reason you used an  ESP8266/NodeMCU wouldn't a ESP32/NodeMCU be a better option

**Comment by jjshoots** [comment]
The primary reason for the NodeMCU is that I had it on hand and a weekend to spare 😂

**Comment by jjshoots** [comment]
@WayneStarkey I've just tested it again, this time with a slightly modified script (updated on master). On my end it seems to work with all 16 drones transmitting GPS information. What may be happening is that the NodeMCU can't really keep up with the packet rate (although I doubt this is the case), or that the scanning device is not picking up the signals fast enough. If you check on OpenDroneID, each drone ping is only detected every ~3 seconds, which is far slower than what the NodeMCU is broadcasting at (~10 Hz). If you let the app run for ~10 minutes, eventually all 16 drones are "in the air".
