### ISSUE TITLE
GPS coordiantes  severial miles away on map

### ISSUE THREAD

**Issue by jjlink** [jjshoots/RemoteIDSpoofer#4]
This is very cool, Thanks. 
I added my GPS coordinates to spoofer.cpp and the 16 drones on the map show-up several miles away. Any idea why?
Thanks!

**Comment by jjshoots** [comment]
Hi, thanks for the issue!

You need to input very specific coordinates, including degrees, minutes, and seconds. They are all on the same line.

To help with debugging, you can remove the noise component to narrow down your GPS coordinates. If you'd like,  send me a message on Discord and I can help you better. My handle is [redacted].

**Comment by jjlink** [comment]
Yes, I got it to the correct GPS coordinates. Thanks!
