### ISSUE TITLE
2. There, input your own GPS coordinates..... how?

### ISSUE THREAD

**Issue by robustini** [jjshoots/RemoteIDSpoofer#6]
Thanks for the code, it works perfectly, but the documentation is not clear.
After wifi connection how to send new gps coordinates?
Is it possible to do it from the smartphone in those two minutes?
This step is not explained.

**Comment by jjshoots** [comment]
Hi, thanks for catching this! I've fixed it in the docs. Apologies for the confusion. After the wifi connection, go to the website `192.168.4.1`, there, you can input the GPS coordinates.

**Comment by robustini** [comment]
Thanks!
