### ISSUE TITLE
Clarification: RemoteID and/or DroneID?

### ISSUE THREAD

**Issue by wspch0p** [jjshoots/RemoteIDSpoofer#7]
Hey,

does this project also spoof/broadcast DJI's DroneID data (Aeroscope detectable) or (FAA style) Remote ID only?

Source indicates opendroneid is used, yet I'm unsure if DJI's DroneID is using the same protocol?

A sample project claiming to spoof Aeroscope detectable DroneID data:
https://github.com/DJISDKUser/ESP8266_DJI_DroneID_Throwie

Kindly asking for clarification.

**Comment by sethmnone** [comment]
> Hey,
> 
> does this project also spoof/broadcast DJI's DroneID data (Aeroscope detectable) or (FAA style) Remote ID only?
> 
> Source indicates opendroneid is used, yet I'm unsure if DJI's DroneID is using the same protocol?
> 
> A sample project claiming to spoof Aeroscope detectable DroneID data: https://github.com/DJISDKUser/ESP8266_DJI_DroneID_Throwie
> 
> Kindly asking for clarification.

It replicates RemoteID broadcasts only. RemoteID is similar to DJI's Drone ID but not the same transmission or protocol. Hope this helps!

**Comment by jjshoots** [comment]
Yep! Whatever @sethmnone mentioned is correct. You can probably modify the code to also broadcast DroneID data if you want, given the linked repo.

**Comment by giovi321** [comment]
Anybody willing to implement DJI Drone ID?
