### ISSUE TITLE
Nothing is showing up

### ISSUE THREAD

**Issue by kireol** [jjshoots/RemoteIDSpoofer#9]
I'm sure it's just me, but I'm not showing any drones.

Steps:

1) Cloned repo as of April 10, 2024
2) Connected board and port trying both esp8266 and esp32 dev boards
3) Successful build and push
4) Connected to ESP_RIDS wifi
5) Set lat and long to my location and saved
6) Set drones to 16 (also tried 1 and 3) and saved
7) clicked "Start Spoofing"
8) Console output showing:
    Ready
    EEPROM found, reusing old values...
    Client Connected
    Starting Spoofers
9) Started "Drone Scanner" app (as well as a few other apps)  in android with bluetooth and wifi on.
10) Walked around a bit in case the phone and esp were too close.
11) Nothing shows up.    
    
If I unplug the esp and connect to wifi again, I see the settings were saved.    

<img width="302" alt="Screenshot 2024-04-11 at 9 32 14 AM" src="https://github.com/jjshoots/RemoteIDSpoofer/assets/3438792/ebd343d4-ae89-4b24-829d-5ed1a5592d02">

![Screenshot_20240411_093112](https://github.com/jjshoots/RemoteIDSpoofer/assets/3438792/8969d391-2a43-4c98-828a-b8a92d94a955)

**Comment by jjshoots** [comment]
One common reason this happens is that the wifi module inside most smartphones are set to throttle wifi. You may have to disable this for the phone to pick up the spoofed drones. Typically, this is done through developer settings on the phone (this is usually uncomplicated and just requires pressing some buttons on the settings page on your phone but you'll have to Google how to do it for your particular model).

Try that, and let me know if it works. :)

**Comment by jjshoots** [comment]
As an aside, what detecting app are you using? I'll test this on my end as well.

**Comment by kireol** [comment]
I happen to be an Android developer, so turning that off was easy, thanks!

Good news.  It worked!

Bad news, so then I changed 1 drone to 16, and now nothing will show up again.  Even tried changing it back to 1.

The app I'm using that did work is Drone Scanner.

**Comment by jjshoots** [comment]
Typically, when spoofing on 16 drones, it takes a solid 5 minutes for the phone to pick up all the signals, even with wifi scan throttling off. And in between power cycles, it takes 2 minutes for the ESP to go from AP mode to broadcast mode (this is so there is an amount of time for the user to set settings).

I would say let it sit for ~10 minutes, and then check back to see if the drones are showing up. If it doesn't, then something else is probably afoot and I'll investigate.

Thanks for the report!

**Comment by jjshoots** [comment]
@kireol any luck?

**Comment by kireol** [comment]
Not yet.  I have tried it a few more times letting it sit for 10 minutes, but can't get it to show again.  Tried on both 8266 and 32.  Going to wipe and try again soon.  Work keeping me busy is all.

**Comment by kireol** [comment]
OK.  I finally had a chance to revisit.  The issue was with my phone.  It's a Samsung Galaxy S21 FE.  They just won't show up in Drone Scanner.

When I switched to a different Android device, the drones show up almost immediately.  Sorry for the false alarm.

**Comment by jjshoots** [comment]
No worries! Glad you got it sorted! :)
